version: "3"
services:
  root:
    build: ./root
    networks:
      app_net:
        ipv4_address: 10.10.0.2
  com:
    build: ./com
    networks:
      app_net:
        ipv4_address: 10.10.0.3
  jpn.com:
    build: ./jpn.com
    networks:
      app_net:
        ipv4_address: 10.10.0.5
  fullresolver:
    build: ./fullresolver
    ports:
      - 53:53/udp
    networks:
      app_net:
        ipv4_address: 10.10.0.4
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
